# jekyll config file for GH Page
title: Bitwarden F-Droid Repository
logo: fdroid/repo/com.x8bit.bitwarden/en-US/icon.png
markdown: GFM
theme: minima
minima:
  skin: auto
exclude:
  - "./fdroid/archive/*"
  - "./metascoop/*"
